### CREATE ATTACHMENT
POST http://localhost:9000/attachments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDE1MTQ5NjgsImV4cCI6MTc0MTUyMjE2OH0.fMRiXgEwGvvMu8IoixvtbapZH8Rv3MXTfksNFe0oTeQ

{
    "title": "Software Engineering Internship",
    "description": "Join our team as a software engineering intern and gain hands-on experience.",
    "company_name": "Tech Corp",
    "application_link": "https://techcorp.com/internship-apply"
}

### GET ALL ATTACHMENTS
GET http://localhost:9000/attachments/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDExMjE1MDIsImV4cCI6MTc0MTEyODcwMn0.hXLt_a-p5nft3wUdSP4t70w2N-eGLrPL-6yRTqIwsac

### GET SINGLE ATTACHMENT
GET http://localhost:9000/attachments/2fff0671-1bd6-4c2c-82bf-bafb5a77ea34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDExMTQwODEsImV4cCI6MTc0MTEyMTI4MX0.F0VFo8yMMuSCN753MCfburBjwJS0ev-3QiI4pISrMpE

### UPDATE ATTACHMENT
Patch http://localhost:9000/attachments/update/2fff0671-1bd6-4c2c-82bf-bafb5a77ea34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDExMTQwODEsImV4cCI6MTc0MTEyMTI4MX0.F0VFo8yMMuSCN753MCfburBjwJS0ev-3QiI4pISrMpE

{
    "title": "Software Engineering Internship",
    "description": "Join our team as a software engineering intern and gain hands-on experience.",
    "company_name": "Tech Corp",
    "application_link": "https://techcorp.com/internship-apply"
}

### APPLY FOR ATTACHMENT
POST http://localhost:9000/attachments/apply/2fff0671-1bd6-4c2c-82bf-bafb5a77ea34
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczNTBjYmRhLWRjM2UtNGIxZS1hNTdmLTk5ZmIxMDZhNGRiOCIsImZpcnN0TmFtZSI6Ik1vcmluZW1haW5hIiwibGFzdE5hbWUiOiJNYWluYSIsImVtYWlsIjoibW9yaW5lZW1haW5hQGdtYWlsLmNvbSIsInByb2ZpbGUiOm51bGwsImNvdmVySW1hZ2UiOm51bGwsImlzVXBkYXRlZCI6dHJ1ZSwidXBkYXRlZEF0IjoiMjAyNS0wMi0yM1QyMzowODo0NC42NjBaIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3NDExMTcyNDYsImV4cCI6MTc0MTEyNDQ0Nn0.Izw3pko9GGRBOOA4weNzVgpuE2TvUzhmkegUUjEWy3I



### attachments for a user
GET http://localhost:9000/attachments/user/attachments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDE1MzM4NTcsImV4cCI6MTc0MTU0MTA1N30.6tczom1s_IdvM-kPvYUVkWWiRTwtFh3_l55Fy1muFt0

### Soft Delete Request:
PATCH http://localhost:9000/attachments/soft-delete/c0fc3b91-94af-4435-804d-6f5319bfdb66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjczNTBjYmRhLWRjM2UtNGIxZS1hNTdmLTk5ZmIxMDZhNGRiOCIsImZpcnN0TmFtZSI6Ik1vcmluZW1haW5hIiwibGFzdE5hbWUiOiJNYWluYSIsImVtYWlsIjoibW9yaW5lZW1haW5hQGdtYWlsLmNvbSIsInByb2ZpbGUiOm51bGwsImNvdmVySW1hZ2UiOm51bGwsImlzVXBkYXRlZCI6dHJ1ZSwidXBkYXRlZEF0IjoiMjAyNS0wMi0yM1QyMzowODo0NC42NjBaIiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3NDExMTcyNDYsImV4cCI6MTc0MTEyNDQ0Nn0.

### Restore Request:
PATCH http://localhost:9000/attachments/restore/c0fc3b91-94af-4435-804d-6f5319bfdb66
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDExMjIyMDYsImV4cCI6MTc0MTEyOTQwNn0.iuAszqsdUS-5p4eozWXx-HclLwz1YCH1zfPgVooB0Wk