### LOGIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email": "anastaciacheptoo@gmail.com",
    "password": "Tash@123"
}


### CHECK TOKEN DETAILS
GET http://localhost:9000/auth/check-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU0ZTY3ZGVjLThkY2UtNDE0MC1hMjJmLWIwZTg5MzE0MzRmOSIsImZpcnN0TmFtZSI6IkNsaW50b24iLCJsYXN0TmFtZSI6Ik9tYXJpIiwiZW1haWwiOiJjbGludG9uYXJhbmlAZ21haWwuY29tIiwicHJvZmlsZSI6bnVsbCwiY292ZXJJbWFnZSI6bnVsbCwiaXNVcGRhdGVkIjpmYWxzZSwidXBkYXRlZEF0IjpudWxsLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDE1MjMzNTQsImV4cCI6MTc0MTUzMDU1NH0.1y80qGXaykO2LFZktsNMNfRcpDk6zcPU-87hIZSdbwU

### LOGOUT
POST http://localhost:9000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU3MmFjMGJhLTEyMDYtNDI5MS1iNzVmLTM2ZjRhZjYzOThlNSIsImZpcnN0TmFtZSI6IkFuYXN0YWNpYSIsImxhc3ROYW1lIjoiQ2hlcHRvbyIsImVtYWlsIjoiYW5hc3RhY2lhY2hlcHRvb0BnbWFpbC5jb20iLCJwcm9maWxlIjpudWxsLCJjb3ZlckltYWdlIjpudWxsLCJpc0NyZWF0ZWQiOmZhbHNlLCJpc1VwZGF0ZWRBdCI6ZmFsc2UsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzQwMzI5Njk1LCJleHAiOjE3NDAzMzY4OTV9._W0BOeLICC7J26dL3GgajyPnH4CBmL4646YYYYXmkmA