### LOGIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{
    "email": "anastaciacheptoo@gmail.com",
    "password": "Tash@123"
}


### CHECK TOKEN DETAILS
GET http://localhost:9000/auth/check-details
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ZjM2NWQ2LTZmODAtNDBlNC1hNzAwLWI1NDBmY2MyYjRiYSIsImZpcnN0TmFtZSI6IkxhbmNlIiwibGFzdE5hbWUiOiJXZXN0IiwiZW1haWwiOiJhbmFzdGFjaWFjaGVwdG9vQGdtYWlsLmNvbSIsInByb2ZpbGUiOm51bGwsImNvdmVySW1hZ2UiOm51bGwsImlzVXBkYXRlZCI6ZmFsc2UsInVwZGF0ZWRBdCI6bnVsbCwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3NDI4MTg2ODUsImV4cCI6MTc0MjgyNTg4NX0.4APstz0YORiu7RO2MUM0q6SYQdoWWgbU9-UVbPAFDbM
### LOGOUT
POST http://localhost:9000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA4ZjM2NWQ2LTZmODAtNDBlNC1hNzAwLWI1NDBmY2MyYjRiYSIsImZpcnN0TmFtZSI6IkxhbmNlIiwibGFzdE5hbWUiOiJXZXN0IiwiZW1haWwiOiJhbmFzdGFjaWFjaGVwdG9vQGdtYWlsLmNvbSIsInByb2ZpbGUiOm51bGwsImNvdmVySW1hZ2UiOm51bGwsImlzVXBkYXRlZCI6ZmFsc2UsInVwZGF0ZWRBdCI6bnVsbCwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE3NDI4MTg2ODUsImV4cCI6MTc0MjgyNTg4NX0.4APstz0YORiu7RO2MUM0q6SYQdoWWgbU9-UVbPAFDbM