### INITIATE PASSWORD RESET (Send reset code to email)
POST http://localhost:9000/users/forgot-password
Content-Type: application/json

{
"email": "anastaciacheptoo@gmail.com"
}

### RESET PASSWORD (After code verification)
POST http://localhost:9000/users/reset-password
Content-Type: application/json

{
"email": "araniclinton@gmail.com",
"resetCode": "446952",
"newPassword": "Bill@123"
}

### VERIFY RESET CODE
POST http://localhost:9000/users/verify-reset-code
Content-Type: application/json

{
"email": "araniclinton@gmail.com",
"resetCode": "964702"
}